/**
 * One-shot migration: move the design-tool placeholder images into the media library.
 *
 * ## Why
 *
 * Every value in `apps/web/src/lib/data/media.ts` is an id on
 * `lh3.googleusercontent.com/aida-public` — Google's AI Studio demo asset host. It is not
 * owned media, and three consequences were measured against the live site rather than
 * assumed:
 *
 * - **It refuses the edge.** A browser gets 200; Cloudflare's image transformer gets 403. So
 *   these images cannot be resized at all, and `$lib/images` deliberately emits no `srcset`
 *   for them — which means their ~495 KB is the *unresized* cost, on a site whose whole point
 *   this session was cutting image weight.
 * - **It is a third-party dependency** on the hero imagery of a live business.
 * - **The admin cannot see or replace it.** The media library knows nothing about these files,
 *   so an editor cannot re-crop or re-host them.
 *
 * ## What it does
 *
 * For each placeholder a template can actually reach: download it, write it to R2 under a
 * fresh UUID, insert a `media_assets` row with the real width, height and byte size, and
 * record the swap in `.stitch/media-substitutions.json` for the generator to apply.
 *
 * `media.ts` itself is **not** touched here. It is generated by `.stitch/gen-media.mjs` and
 * the repo forbids hand-editing it, so the substitution map is what the generator reads.
 *
 * ## Why only the reachable ones
 *
 * The generator emits 72 placeholder references. Six are reachable from a template; the rest
 * are dead weight in a generated file nobody renders. Migrating all 72 would mean paying
 * storage and time for images no page can display, so the script selects by reachability and
 * says what it skipped.
 *
 * ## Running it
 *
 * ```sh
 * pnpm --filter @banggai/admin exec tsx scripts/replace-placeholder-media.ts
 * node .stitch/gen-media.mjs
 * ```
 *
 * Idempotent: a placeholder already present in the substitutions file is skipped, so a re-run
 * after a partial failure resumes rather than duplicating. Safe to delete once both branches
 * have run it.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { neon } from '@neondatabase/serverless';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');

const AIDA = 'https://lh3.googleusercontent.com/aida-public/';
const BUCKET = 'banggaiescape-media';
const MEDIA_BASE = 'https://media.banggaiescape.com';
const SUBSTITUTIONS = resolve(repoRoot, '.stitch/media-substitutions.json');
const WORK = resolve(repoRoot, 'node_modules/.cache/placeholder-media');

/**
 * The `media.ts` keys a template actually reaches, and the AIDA id behind each.
 *
 * Derived by scanning the source rather than transcribed. An earlier hand-written version of
 * this list was wrong in a way that would have been very hard to see: a mistyped base64 id is
 * still a plausible-looking string, and it would have quietly pointed at the wrong picture.
 */
function reachablePlaceholders(): Map<string, string> {
	const mediaSource = readFileSync(
		resolve(repoRoot, 'apps/web/src/lib/data/media.ts'),
		'utf8',
	);

	// key -> aida id, from the generator's own output shape.
	const byKey = new Map<string, string>();
	for (const match of mediaSource.matchAll(/'([a-z0-9-]+)':\s*'(AB6[A-Za-z0-9_-]+)'/g)) {
		byKey.set(match[1], match[2]);
	}

	// A template names an image as media['page-slug']['alt-slug']; the *last* key identifies it.
	const reached = new Set<string>();
	for (const path of walk(resolve(repoRoot, 'apps/web/src'))) {
		if (!path.endsWith('.svelte')) continue;

		const text = readFileSync(path, 'utf8');
		for (const match of text.matchAll(/media(?:\.\w+)*((?:\[['"][^'"]+['"]\])+)/g)) {
			const keys = [...match[1].matchAll(/\[['"]([^'"]+)['"]\]/g)].map((k) => k[1]);
			const key = keys.at(-1);
			if (key) reached.add(key);
		}
	}

	const wanted = new Map<string, string>();
	for (const key of reached) {
		const id = byKey.get(key);
		if (id) wanted.set(id, key);
	}

	return wanted;
}

function walk(dir: string): string[] {
	const out: string[] = [];

	for (const entry of readdirSync(dir)) {
		const path = resolve(dir, entry);

		// `.isDirectory()`, not the Stat object itself: a Stat is always truthy, which
		// recurses into files and fails with ENOTDIR on the first one it meets.
		if (statSync(path).isDirectory()) out.push(...walk(path));
		else out.push(path);
	}

	return out;
}

type Substitution = { url: string; key: string; assetId: string };

function loadSubstitutions(): Record<string, Substitution> {
	if (!existsSync(SUBSTITUTIONS)) return {};

	try {
		return JSON.parse(readFileSync(SUBSTITUTIONS, 'utf8')) as Record<string, Substitution>;
	} catch {
		return {};
	}
}

/** Byte length of a JPEG/PNG/WebP header, without pulling in an image library. */
function imageSize(bytes: Uint8Array): { width: number; height: number } | null {
	const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

	// PNG: IHDR at a fixed offset.
	if (bytes[0] === 0x89 && bytes[1] === 0x50) {
		return { width: view.getUint32(16), height: view.getUint32(20) };
	}

	// JPEG: walk the segment markers to the first SOFn.
	if (bytes[0] === 0xff && bytes[1] === 0xd8) {
		let offset = 2;
		while (offset + 9 < bytes.length) {
			if (bytes[offset] !== 0xff) {
				offset += 1;
				continue;
			}
			const marker = bytes[offset + 1];
			// SOF0..SOF15, skipping the non-frame markers in that range.
			if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
				return { height: view.getUint16(offset + 5), width: view.getUint16(offset + 7) };
			}
			offset += 2 + view.getUint16(offset + 2);
		}
	}

	return null;
}

async function main() {
	const databaseUrl = process.env.DATABASE_URL;
	if (!databaseUrl) throw new Error('DATABASE_URL is not set. Run this through the admin package.');

	const sql = neon(databaseUrl);
	const existing = loadSubstitutions();
	const wanted = reachablePlaceholders();

	mkdirSync(WORK, { recursive: true });

	const next: Record<string, Substitution> = { ...existing };
	let added = 0;
	let skipped = 0;
	let bytes = 0;

	for (const [aidaId, key] of wanted) {
		if (existing[aidaId]) {
			skipped += 1;
			continue;
		}

		const response = await fetch(`${AIDA}${aidaId}=w2000`);
		if (!response.ok) {
			throw new Error(`${key}: placeholder host answered ${response.status} for ${aidaId}`);
		}

		const body = new Uint8Array(await response.arrayBuffer());
		const size = imageSize(body);
		if (!size) throw new Error(`${key}: could not read the dimensions of ${aidaId}`);

		const objectKey = `${crypto.randomUUID()}.jpg`;
		const local = resolve(WORK, objectKey);
		writeFileSync(local, body);

		execFileSync(
			'pnpm',
			[
				'exec',
				'wrangler',
				'r2',
				'object',
				'put',
				`${BUCKET}/${objectKey}`,
				'--file',
				local,
				'--content-type',
				'image/jpeg',
				'--remote',
			],
			{ cwd: resolve(repoRoot, 'apps/admin'), stdio: 'pipe' },
		);

		const inserted = await sql`
			insert into media_assets (id, object_key, original_name, mime_type, byte_size, width, height, alt_text)
			values (
				gen_random_uuid(),
				${objectKey},
				${`${key}.jpg`},
				'image/jpeg',
				${body.byteLength},
				${size.width},
				${size.height},
				${null}
			)
			returning id
		`;

		const assetId = String(inserted[0].id);
		next[aidaId] = { url: `${MEDIA_BASE}/${objectKey}`, key, assetId };

		added += 1;
		bytes += body.byteLength;
		console.log(
			`  ${key} -> ${objectKey} (${size.width}x${size.height}, ${Math.round(body.byteLength / 1024)} KB)`,
		);
	}

	writeFileSync(SUBSTITUTIONS, `${JSON.stringify(next, null, '\t')}\n`);

	console.log(
		`\n${added} migrated, ${skipped} already done, ${Math.round(bytes / 1024)} KB moved into R2.`,
	);
	console.log(
		`${wanted.size} of the generator's placeholders are reachable from a template; the rest ` +
			'are left alone deliberately.',
	);
	console.log('\nNow run:  node .stitch/gen-media.mjs');
}

await main();
