/**
 * One-shot migration: move the design-tool placeholder images into the media library.
 *
 * ## Why
 *
 * Every value in `apps/web/src/lib/data/media.ts` is an id on
 * `lh3.googleusercontent.com/aida-public` — Google's AI Studio demo asset host. It is not
 * owned media, and three consequences were measured against the live site rather than
 * assumed:
 *
 * - **It refuses the edge.** A browser gets 200; Cloudflare's image transformer gets 403. So
 *   these images cannot be resized at all, and `$lib/images` deliberately emits no `srcset`
 *   for them — which means their ~495 KB is the *unresized* cost, on a site whose whole point
 *   this session was cutting image weight.
 * - **It is a third-party dependency** on the hero imagery of a live business.
 * - **The admin cannot see or replace it.** The media library knows nothing about these files,
 *   so an editor cannot re-crop or re-host them.
 *
 * ## What it does
 *
 * For each placeholder a template can actually reach: download it, write it to R2 under a
 * fresh UUID, insert a `media_assets` row with the real width, height and byte size, and
 * record the swap in `.stitch/media-substitutions.json` for the generator to apply.
 *
 * `media.ts` itself is **not** touched here. It is generated by `.stitch/gen-media.mjs` and
 * the repo forbids hand-editing it, so the substitution map is what the generator reads.
 *
 * ## Why only the reachable ones
 *
 * The generator emits 72 placeholder references. Six are reachable from a template; the rest
 * are dead weight in a generated file nobody renders. Migrating all 72 would mean paying
 * storage and time for images no page can display, so the script selects by reachability and
 * says what it skipped.
 *
 * ## Running it
 *
 * ```sh
 * pnpm --filter @banggai/admin exec tsx scripts/replace-placeholder-media.ts
 * node .stitch/gen-media.mjs
 * ```
 *
 * Idempotent: a placeholder already present in the substitutions file is skipped, so a re-run
 * after a partial failure resumes rather than duplicating. Safe to delete once both branches
 * have run it.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { neon } from '@neondatabase/serverless';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');

const AIDA = 'https://lh3.googleusercontent.com/aida-public/';
const BUCKET = 'banggaiescape-media';
const MEDIA_BASE = 'https://media.banggaiescape.com';
const SUBSTITUTIONS = resolve(repoRoot, '.stitch/media-substitutions.json');
const WORK = resolve(repoRoot, 'node_modules/.cache/placeholder-media');

/** What a reachable key currently points at, and therefore what still needs doing to it. */
type Reachable = {
	/** The `media.ts` key. */
	key: string;
	/** The bare `aida-public` id, when it is still one. */
	aidaId: string | null;
	/** True when `media.ts` already holds a media-library URL for this key. */
	migrated: boolean;
};

/**
 * Every `media.ts` key a template actually reaches, and the state each is in.
 *
 * Derived by scanning the source rather than transcribed. An earlier hand-written version of
 * this list was wrong in a way that would have been very hard to see: a mistyped base64 id is
 * still a plausible-looking string, and it would have quietly pointed at the wrong picture.
 *
 * Both states are reported, which matters more than it sounds. Once a key has been migrated its
 * value in `media.ts` is a URL rather than an `AB6…` id, so a scan that only recognises ids
 * finds *nothing* to do and reports "0 reachable" — indistinguishable from a run that had
 * genuinely found no reachable placeholders. That is the wrong answer stated confidently, and
 * it is the answer this script gives about itself immediately after it succeeds.
 */
function reachablePlaceholders(): Reachable[] {
	const mediaSource = readFileSync(resolve(repoRoot, 'apps/web/src/lib/data/media.ts'), 'utf8');

	// key -> current value, from the generator's own output shape. The value is either an
	// `AB6…` id or a full media-library URL, and which one it is *is* the migration state.
	const byKey = new Map<string, string>();
	for (const match of mediaSource.matchAll(/'([a-z0-9-]+)':\s*'([^']+)'/g)) {
		byKey.set(match[1], match[2]);
	}

	// A template names an image as media['page-slug']['alt-slug']; the *last* key identifies it.
	const reached = new Set<string>();
	for (const path of walk(resolve(repoRoot, 'apps/web/src'))) {
		if (!path.endsWith('.svelte')) continue;

		const text = readFileSync(path, 'utf8');
		for (const match of text.matchAll(/media(?:\.\w+)*((?:\[['"][^'"]+['"]\])+)/g)) {
			const keys = [...match[1].matchAll(/\[['"]([^'"]+)['"]\]/g)].map((k) => k[1]);
			const key = keys.at(-1);
			if (key) reached.add(key);
		}
	}

	return [...reached]
		.map((key) => {
			const value = byKey.get(key);

			if (value === undefined) return null;
			if (value.startsWith('http')) return { key, aidaId: null, migrated: true };

			return { key, aidaId: value, migrated: false };
		})
		.filter((entry): entry is Reachable => entry !== null)
		.sort((a, b) => a.key.localeCompare(b.key));
}

function walk(dir: string): string[] {
	const out: string[] = [];

	for (const entry of readdirSync(dir)) {
		const path = resolve(dir, entry);

		// `.isDirectory()`, not the Stat object itself: a Stat is always truthy, which
		// recurses into files and fails with ENOTDIR on the first one it meets.
		if (statSync(path).isDirectory()) out.push(...walk(path));
		else out.push(path);
	}

	return out;
}

type Substitution = { url: string; key: string; assetId: string };

function loadSubstitutions(): Record<string, Substitution> {
	if (!existsSync(SUBSTITUTIONS)) return {};

	try {
		return JSON.parse(readFileSync(SUBSTITUTIONS, 'utf8')) as Record<string, Substitution>;
	} catch {
		return {};
	}
}

/** Byte length of a JPEG/PNG/WebP header, without pulling in an image library. */
function imageSize(bytes: Uint8Array): { width: number; height: number } | null {
	const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

	// PNG: IHDR at a fixed offset.
	if (bytes[0] === 0x89 && bytes[1] === 0x50) {
		return { width: view.getUint32(16), height: view.getUint32(20) };
	}

	// JPEG: walk the segment markers to the first SOFn.
	if (bytes[0] === 0xff && bytes[1] === 0xd8) {
		let offset = 2;
		while (offset + 9 < bytes.length) {
			if (bytes[offset] !== 0xff) {
				offset += 1;
				continue;
			}
			const marker = bytes[offset + 1];
			// SOF0..SOF15, skipping the non-frame markers in that range.
			if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
				return { height: view.getUint16(offset + 5), width: view.getUint16(offset + 7) };
			}
			offset += 2 + view.getUint16(offset + 2);
		}
	}

	return null;
}

async function main() {
	const databaseUrl = process.env.DATABASE_URL;
	if (!databaseUrl) throw new Error('DATABASE_URL is not set. Run this through the admin package.');

	const sql = neon(databaseUrl);
	const existing = loadSubstitutions();
	const reachable = reachablePlaceholders();

	mkdirSync(WORK, { recursive: true });

	const next: Record<string, Substitution> = { ...existing };
	// Counted up front so the summary can say what it found as well as what it did. A report
	// that only counts changes cannot distinguish "nothing to do because it is all done" from
	// "nothing to do because the scan found nothing", and those need different reactions.
	const alreadyMigrated = reachable.filter((entry) => entry.migrated).length;
	const pending = reachable.filter((entry) => !entry.migrated);

	let added = 0;
	let skipped = 0;
	let bytes = 0;

	for (const { key, aidaId } of pending) {
		// `aidaId` is non-null for every pending entry; the filter above is what guarantees it,
		// and an assertion is cheaper than a `!` on a type the compiler cannot see.
		if (!aidaId) continue;

		if (existing[aidaId]) {
			// In the map but not yet applied to `media.ts`, which happens when a run was
			// interrupted between writing the map and regenerating.
			skipped += 1;
			console.log(`  ${key}: already in the map, regenerate media.ts to apply it`);
			continue;
		}

		const response = await fetch(`${AIDA}${aidaId}=w2000`);
		if (!response.ok) {
			throw new Error(`${key}: placeholder host answered ${response.status} for ${aidaId}`);
		}

		const body = new Uint8Array(await response.arrayBuffer());
		const size = imageSize(body);
		if (!size) throw new Error(`${key}: could not read the dimensions of ${aidaId}`);

		const objectKey = `${crypto.randomUUID()}.jpg`;
		const local = resolve(WORK, objectKey);
		writeFileSync(local, body);

		execFileSync(
			'pnpm',
			[
				'exec',
				'wrangler',
				'r2',
				'object',
				'put',
				`${BUCKET}/${objectKey}`,
				'--file',
				local,
				'--content-type',
				'image/jpeg',
				'--remote',
			],
			{ cwd: resolve(repoRoot, 'apps/admin'), stdio: 'pipe' },
		);

		const inserted = await sql`
			insert into media_assets (id, object_key, original_name, mime_type, byte_size, width, height, alt_text)
			values (
				gen_random_uuid(),
				${objectKey},
				${`${key}.jpg`},
				'image/jpeg',
				${body.byteLength},
				${size.width},
				${size.height},
				${null}
			)
			returning id
		`;

		const assetId = String(inserted[0].id);
		next[aidaId] = { url: `${MEDIA_BASE}/${objectKey}`, key, assetId };

		added += 1;
		bytes += body.byteLength;
		console.log(
			`  ${key} -> ${objectKey} (${size.width}x${size.height}, ${Math.round(body.byteLength / 1024)} KB)`,
		);
	}

	writeFileSync(SUBSTITUTIONS, `${JSON.stringify(next, null, '\t')}\n`);

	console.log(
		`\n${reachable.length} placeholder(s) a template can reach: ` +
			`${alreadyMigrated} already migrated, ${added} migrated now, ${skipped} awaiting a regenerate.`,
	);
	if (added > 0) console.log(`  ${Math.round(bytes / 1024)} KB moved into R2.`);
	console.log(
		`The generator's other placeholders are unreachable from any template and are left ` +
			'alone deliberately: migrating them would mean paying storage for images no page ' +
			'can display.',
	);
	console.log('\nNow run:  node .stitch/gen-media.mjs');
}

await main();
