/**
 * One-shot migration: move the design-tool placeholder images into the media library.
 *
 * ## Why
 *
 * Every value in `apps/web/src/lib/data/media.ts` was an id on
 * `lh3.googleusercontent.com/aida-public` — Google's AI Studio demo asset host. It is not
 * owned media, and three consequences were measured against the live site rather than
 * assumed:
 *
 * - **It refused the edge.** A browser got 200; Cloudflare's image transformer got 403. So
 *   those images could not be resized at all, and `$lib/images` deliberately emitted no
 *   `srcset` for them — which means their ~495 KB was the *unresized* cost, on a site whose
 *   whole point this session was cutting image weight.
 * - **It was a third-party dependency** on the hero imagery of a live business.
 * - **The admin could not see or replace it.** The media library knew nothing about these
 *   files, so an editor had no way to re-crop or re-host them.
 *
 * ## What it does, in two halves
 *
 * **Fetch and upload** — for each placeholder that is *still* an `aida-public` id: download it,
 * write it to R2 under a fresh UUID, and record the swap in `.stitch/media-substitutions.json`
 * for the generator to apply. This half happens at most once per image, ever.
 *
 * **Register in the library** — for every reachable placeholder, migrated or not: make sure a
 * `media_assets` row exists for its R2 object, inserting one if the database in front of this
 * process has none. This half is what makes the script useful against *more than one*
 * database, which is not hypothetical: the R2 objects and the substitution map are shared, but
 * each Neon branch has its own rows and its own uuids, so a single run leaves every other
 * branch's media library missing seven images.
 *
 * The halves are separate on purpose. The first is expensive and happens once; the second is
 * one `insert … on conflict do nothing` per image and has to be re-runnable per environment.
 * The obvious single implementation — "skip anything already in the map" — gets the second
 * half wrong in exactly the case it exists for, because an image already in the map looks the
 * same whether or not *this* database knows about it.
 *
 * `media.ts` itself is **not** touched here. It is generated by `.stitch/gen-media.mjs` and
 * the repo forbids hand-editing it, so the substitution map is what the generator reads.
 *
 * ## Why only the reachable ones
 *
 * The generator emits 72 placeholder references. Seven are reachable from a template; the rest
 * are dead weight in a generated file nobody renders. Migrating all 72 would mean paying
 * storage and time for images no page can display, so the script selects by reachability and
 * reports what it found rather than what it skipped.
 *
 * ## Running it
 *
 * ```sh
 * pnpm --filter @banggai/admin exec tsx scripts/replace-placeholder-media.ts
 * node .stitch/gen-media.mjs
 * ```
 *
 * `DATABASE_URL` decides which database gets the rows; `wrangler`'s token decides which R2
 * bucket gets the objects. Pointing `DATABASE_URL` at another branch and re-running is
 * therefore the whole procedure for registering the same images there. Safe to run any number
 * of times, in any order, against any branch.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { neon } from '@neondatabase/serverless';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');

const AIDA = 'https://lh3.googleusercontent.com/aida-public/';
const BUCKET = 'banggaiescape-media';
const MEDIA_BASE = 'https://media.banggaiescape.com';
const SUBSTITUTIONS = resolve(repoRoot, '.stitch/media-substitutions.json');
const WORK = resolve(repoRoot, 'node_modules/.cache/placeholder-media');

/**
 * What one design image now is.
 *
 * `width`, `height` and `byteSize` are here rather than looked up because the register half
 * has to work against a database that has never seen these images, and re-downloading 2 MB to
 * measure files this script already measured is a waste with no compensating benefit. They are
 * also the *source* of the values written to `media_assets`, not a copy of them.
 *
 * There is deliberately no `assetId`. A row's uuid is per-database, and this map is shared
 * across branches, so a uuid recorded here would be wrong everywhere except the database that
 * happened to run first. The R2 object key is the stable identity, and it is already in `url`.
 */
type Substitution = {
	url: string;
	key: string;
	width: number;
	height: number;
	byteSize: number;
};

/** A `media.ts` key a template can reach, and the state it is in. */
type Reachable = {
	/** The `media.ts` key. */
	key: string;
	/** The bare `aida-public` id, or null when the key already holds a media-library URL. */
	aidaId: string | null;
	/** The media-library URL, when the key has been migrated. */
	url: string | null;
};

/** The R2 object key inside a media URL. */
const objectKeyOf = (url: string): string => url.slice(`${MEDIA_BASE}/`.length);

/**
 * Drop a field an earlier version of this script recorded and that is now actively wrong.
 *
 * The old map carried a `media_assets` **uuid**. That was a mistake: the map is shared across
 * Neon branches and a row's uuid is not, so the value was correct in exactly one database and
 * misleading in every other one — and nothing read it, so it looked like harmless bookkeeping
 * rather than a claim that could not be true. The R2 object key is the identity that *is*
 * shared, and it is already in `url`.
 */
function dropPerDatabaseIds(map: Record<string, Substitution>): boolean {
	let changed = false;

	for (const [mapKey, entry] of Object.entries(map)) {
		if (!('assetId' in entry)) continue;

		const { assetId: _discarded, ...rest } = entry as Substitution & { assetId?: string };
		map[mapKey] = rest as Substitution;
		changed = true;
	}

	return changed;
}

/**
 * Every `media.ts` key a template actually reaches, and the state each is in.
 *
 * Derived by scanning the source rather than transcribed. An earlier hand-written version of
 * this list was wrong in a way that would have been very hard to see: a mistyped base64 id is
 * still a plausible-looking string, and it would have quietly pointed at the wrong picture.
 *
 * Both states are reported, which matters more than it sounds. Once a key is migrated its value
 * in `media.ts` is a URL rather than an `AB6…` id, so a scan that only recognises ids finds
 * *nothing* to fetch — and "nothing to fetch" is indistinguishable from "nothing reachable at
 * all", which is a very different thing to be true.
 */
function reachablePlaceholders(): Reachable[] {
	const mediaSource = readFileSync(resolve(repoRoot, 'apps/web/src/lib/data/media.ts'), 'utf8');

	// key -> current value, from the generator's own output shape. The value is either an
	// `AB6…` id or a full media-library URL, and which one it is *is* the migration state.
	const byKey = new Map<string, string>();
	for (const match of mediaSource.matchAll(/'([a-z0-9-]+)':\s*'([^']+)'/g)) {
		byKey.set(match[1], match[2]);
	}

	// A template names an image as `media['page-slug']['alt-slug']`; the *last* key identifies it.
	const reached = new Set<string>();
	for (const path of walk(resolve(repoRoot, 'apps/web/src'))) {
		if (!path.endsWith('.svelte')) continue;

		const text = readFileSync(path, 'utf8');
		for (const match of text.matchAll(/media(?:\.\w+)*((?:\[['"][^'"]+['"]\])+)/g)) {
			const keys = [...match[1].matchAll(/\[['"]([^'"]+)['"]\]/g)].map((k) => k[1]);
			const key = keys.at(-1);
			if (key) reached.add(key);
		}
	}

	return [...reached]
		.map((key): Reachable | null => {
			const value = byKey.get(key);
			if (value === undefined) return null;

			return value.startsWith('http')
				? { key, aidaId: null, url: value }
				: { key, aidaId: value, url: null };
		})
		.filter((entry): entry is Reachable => entry !== null)
		.sort((a, b) => a.key.localeCompare(b.key));
}

function walk(dir: string): string[] {
	const out: string[] = [];

	for (const entry of readdirSync(dir)) {
		const path = resolve(dir, entry);

		// `.isDirectory()`, not the Stat object itself: a Stat is always truthy, which recurses
		// into files and fails with ENOTDIR on the first one it meets.
		if (statSync(path).isDirectory()) out.push(...walk(path));
		else out.push(path);
	}

	return out;
}

function loadSubstitutions(): Record<string, Substitution> {
	if (!existsSync(SUBSTITUTIONS)) return {};

	try {
		return JSON.parse(readFileSync(SUBSTITUTIONS, 'utf8')) as Record<string, Substitution>;
	} catch {
		return {};
	}
}

/** Byte length of a JPEG/PNG/WebP header, without pulling in an image library. */
function imageSize(bytes: Uint8Array): { width: number; height: number } | null {
	const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

	// PNG: IHDR at a fixed offset.
	if (bytes[0] === 0x89 && bytes[1] === 0x50) {
		return { width: view.getUint32(16), height: view.getUint32(20) };
	}

	// JPEG: walk the segment markers to the first SOFn.
	if (bytes[0] === 0xff && bytes[1] === 0xd8) {
		let offset = 2;
		while (offset + 9 < bytes.length) {
			if (bytes[offset] !== 0xff) {
				offset += 1;
				continue;
			}
			const marker = bytes[offset + 1];
			// SOF0..SOF15, skipping the non-frame markers in that range.
			if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
				return { height: view.getUint16(offset + 5), width: view.getUint16(offset + 7) };
			}
			offset += 2 + view.getUint16(offset + 2);
		}
	}

	return null;
}

/** Fetch the bytes for a placeholder, preferring the local cache this script left behind. */
async function fetchImage(url: string, cacheKey: string): Promise<Uint8Array> {
	const cached = resolve(WORK, cacheKey);
	if (existsSync(cached)) return new Uint8Array(readFileSync(cached));

	const response = await fetch(url);
	if (!response.ok) throw new Error(`${url} answered ${response.status}`);

	return new Uint8Array(await response.arrayBuffer());
}

function upload(objectKey: string, local: string): void {
	execFileSync(
		'pnpm',
		[
			'exec',
			'wrangler',
			'r2',
			'object',
			'put',
			`${BUCKET}/${objectKey}`,
			'--file',
			local,
			'--content-type',
			'image/jpeg',
			'--remote',
		],
		{ cwd: resolve(repoRoot, 'apps/admin'), stdio: 'pipe' },
	);
}

/**
 * Fill in the measurements a map entry is missing.
 *
 * The map gained `width`/`height`/`byteSize` after its first seven entries were written, so an
 * existing map has entries without them. They are recovered from the local cache this script
 * left behind, keyed by R2 object key — which is why the cache is named after the object rather
 * than the AIDA id. Only if the cache is gone does it fall back to fetching, and it says so,
 * because a silent 2 MB re-download is the kind of thing that should be visible in a log.
 */
async function withMeasurements(entry: Substitution): Promise<Substitution> {
	if (entry.width && entry.height && entry.byteSize) return entry;

	const objectKey = objectKeyOf(entry.url);
	const fromCache = resolve(WORK, objectKey);

	if (!existsSync(fromCache)) {
		console.log(`  ${entry.key}: cache miss, re-fetching to measure ${objectKey}`);
	}

	const body = await fetchImage(entry.url, objectKey);
	const size = imageSize(body);
	if (!size) throw new Error(`${entry.key}: could not measure ${objectKey}`);

	return { ...entry, width: size.width, height: size.height, byteSize: body.byteLength };
}

async function main() {
	const databaseUrl = process.env.DATABASE_URL;
	if (!databaseUrl) throw new Error('DATABASE_URL is not set. Run this through the admin package.');

	const sql = neon(databaseUrl);
	const existing = loadSubstitutions();
	const reachable = reachablePlaceholders();

	mkdirSync(WORK, { recursive: true });

	const map: Record<string, Substitution> = { ...existing };

	if (dropPerDatabaseIds(map)) {
		console.log('  dropped a stale per-database assetId from the substitutions map');
	}

	let fetched = 0;
	let fetchedBytes = 0;

	// ---- Half one: fetch and upload anything still pointing at the demo host. ----
	for (const { key, aidaId } of reachable) {
		if (!aidaId) continue;

		// Already mapped but not yet applied to `media.ts`, which is what an interrupted run
		// looks like: the map is written before the generator is re-run.
		if (existing[aidaId]) {
			console.log(`  ${key}: already mapped, run \`node .stitch/gen-media.mjs\` to apply it`);
			continue;
		}

		const body = await fetchImage(`${AIDA}${aidaId}=w2000`, `${aidaId}.jpg`);
		const size = imageSize(body);
		if (!size) throw new Error(`${key}: could not read the dimensions of ${aidaId}`);

		const objectKey = `${crypto.randomUUID()}.jpg`;
		const local = resolve(WORK, objectKey);
		writeFileSync(local, body);
		upload(objectKey, local);

		map[aidaId] = {
			url: `${MEDIA_BASE}/${objectKey}`,
			key,
			width: size.width,
			height: size.height,
			byteSize: body.byteLength,
		};

		fetched += 1;
		fetchedBytes += body.byteLength;
		console.log(
			`  ${key} -> ${objectKey} (${size.width}x${size.height}, ${Math.round(body.byteLength / 1024)} KB)`,
		);
	}

	// ---- Half two: make sure *this* database has a row for every reachable image. ----
	//
	// Keyed on the R2 object, which is the one identity shared across branches. `on conflict`
	// rather than a read-then-write, so two runs against the same database cannot both insert.
	let registered = 0;
	let alreadyPresent = 0;

	for (const { key, aidaId, url } of reachable) {
		// Located by AIDA id while the key is still a placeholder, and by its `media.ts` key
		// once it is not — at which point the AIDA id survives only inside the map. Both routes
		// return the map's own key alongside the entry, because the enriched entry has to be
		// written back under *that* key. Returning the entry on its own is what left the first
		// seven map entries without their measurements: the values reached the database and
		// never reached the file that is supposed to be the record of them.
		const found = aidaId ? ([aidaId, map[aidaId]] as const) : url ? byKey(map, key) : undefined;
		if (!found) continue;

		const [mapKey, mapped] = found;
		const entry = await withMeasurements(mapped);
		map[mapKey] = entry;

		const inserted = await sql`
			insert into media_assets (id, object_key, original_name, mime_type, byte_size, width, height, alt_text)
			values (
				gen_random_uuid(),
				${objectKeyOf(entry.url)},
				${`${key}.jpg`},
				'image/jpeg',
				${entry.byteSize},
				${entry.width},
				${entry.height},
				${null}
			)
			on conflict (object_key) do nothing
			returning id
		`;

		if (inserted.length > 0) {
			registered += 1;
		} else {
			alreadyPresent += 1;
		}
	}

	writeFileSync(SUBSTITUTIONS, `${JSON.stringify(map, null, '\t')}\n`);

	const migrated = reachable.filter((entry) => entry.url !== null).length;
	console.log(
		`\n${reachable.length} placeholder(s) a template can reach: ${migrated} migrated, ` +
			`${fetched} fetched now.`,
	);
	if (fetched > 0) console.log(`  ${Math.round(fetchedBytes / 1024)} KB moved into R2.`);
	console.log(`Media library: ${registered} row(s) added, ${alreadyPresent} already present.`);
	console.log(
		`The generator's other placeholders are unreachable from any template and are left ` +
			'alone deliberately: migrating them would mean paying storage for images no page ' +
			'can display.',
	);
	if (fetched > 0) console.log('\nNow run:  node .stitch/gen-media.mjs');
}

/** The map's own key and entry for a `media.ts` key, for one whose AIDA id `media.ts` has dropped. */
function byKey(
	map: Record<string, Substitution>,
	key: string,
): readonly [string, Substitution] | undefined {
	for (const [mapKey, entry] of Object.entries(map)) {
		if (entry.key === key) return [mapKey, entry] as const;
	}

	return undefined;
}

await main();
